### ISSUE TITLE
runsnp failing in AMRplusplus with error from AMRplusplus_SNP script

### ISSUE THREAD

**Issue by LLansing** [Isabella136/AmrPlusPlus_SNP#19]
Reposting an issue I raised on the AMRplusplus repository:

 I have ran AMRplusplus and I noticed 3 samples missing from the SNPconfirmed_AMR_analytic_matrix.csv. The 3 missing samples all failed during the run, showing the following message:

> [88/801dcb] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA02e_t2_M)` terminated with an error exit status (1) -- Error is ignored
[98/073afc] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA01e_t2_M)` terminated with an error exit status (1) -- Error is ignored
[5d/62f34d] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA03u_t2_M)` terminated with an error exit status (1) -- Error is ignored

And each show a similar error in the `.command.err` files:

> \+ nxf_launch
\+ /bin/bash -uex <root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/.command.sh
\+ cp -r <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/config.ini <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/data <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/genes-issues.md <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/LICENSE <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/README.md <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification_Processes <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification.py <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification_Tools <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/usage.md .
\+ python3 SNP_Verification.py -c config.ini -a -i CRA02e_t2_M.alignment.sam -o CRA02e_t2_M_AMR_SNPs --count_matrix AMR_analytic_matrix.csv
Traceback (most recent call last):
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification.py", line 213, in <module>
    verify(read, gene, config)
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/__init__.py", line 26, in verify
    checkResult = NonsenseCheck(read, gene, mapOfInterest, seqOfInterest)   #Checks for nonsense previously found in literature and for new nonsense
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 9, in NonsenseCheck
    return verifyNonsense(read, gene, stopLocation, mapOfInterest)
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 37, in verifyNonsense
    findNonsenseLocation()
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 24, in findNonsenseLocation
    elif stopLocation < queryIndex:
TypeError: '<' not supported between instances of 'int' and 'str'

_Originally posted by @LLansing in https://github.com/Microbial-Ecology-Group/AMRplusplus/issues/2#issuecomment-1292779248_

**Comment by Isabella136** [comment]
Hi @LLansing 
Thanks for reporting this issue.
I believe that the new changes I've made should fix the problem.
Let me know if you run into the same or any other issues.

Best,
Nathalie

**Comment by LLansing** [comment]
@Isabella136 this fix seems to have solved my error, thank you!
